### ISSUE TITLE
Testing: Inverse Properties module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/InverseProperties#1]
The Inverse Properties module allows administrators to define inverse properties between resources (items, item sets, media) so that property values can be concretely linked in both directions. In effect, it enables a custom implementation of [`owl:inverseOf`](https://www.w3.org/TR/owl-ref/#inverseOf-def) integrated with Omeka S resource templates.

Or, put another way, this module can explicitly link two resources together using inverse properties. This is in contrast to the existing "linked resources" feature, which establishes an implicit linkage. An example of an inverse property relation is `bibo:citedBy owl:inverseOf bibo:cites`, which means that if **Document A** cites **Document B**, then **Document B** will declare that it is cited by **Document A**. This module makes this explicit linkage automatic.

To test this, you must already have at least one resource template that has properties using the default or resource data types. Install the module and go to "Modules" > "Inverse Properties."  Edit a (Inverse Properties) resource template, set a few inverse properties, and save. The properties must save as expected and the table data must be accurate. Then, create an item and assign it the resource template you just edited. On every property for which you created inverses, click on "Omeka resource" and "Item". Select an item and save the form. On the item's show page, click on the resource you just linked and see if the inverse property value was created automatically.

Do this for several resource templates and for several inverse properties, making sure the inverse properties were created.

**Comment by katknow** [comment]
This seems to be working as described--have made several different templates with different values and all have worked & linked automatically.
