### ISSUE TITLE
Documentation: Inverse Properties module

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/InverseProperties#2]
See #1

**Comment by katknow** [comment]
[Here's a draft ](https://github.com/katknow/Drafts/blob/2b0efc57c768885c7c6ee12d0406a983c36fa425/inverseproperties.md) of the documentation. Please let me know what changes you'd like me to make. It feels a bit short, but I wasn't sure what else to add.

**Comment by jimsafley** [comment]
It looks great. This is a simple module and doesn't need further explanation.

**Comment by allanaaa** [comment]
@katknow Can you publish this into a pull request on the docs repository?

**Comment by katknow** [comment]
@allanaaa there should be an inverse-properties branch on there with the new documentation--should I do a direct pull request to the main branch?

**Comment by allanaaa** [comment]
Oh, I see it! No worries, I'll take care of it.
